### ISSUE TITLE
[Proposal] Removing extra request in HTTPStore

### ISSUE THREAD

**Issue by ilan-gold** [gzuidhof/zarr.js#10]
If I understand this right the `containsItem` function contains a request for the data in question which effectively doubles the number of requests/data transferred.  It seems you were aware of this when writing this package originally so I wanted to double back to it and see if you had any strong feelings either way:

https://github.com/gzuidhof/zarr.js/blob/ab6f43b639ac85f49772beaf92814656f8e075c5/src/core/index.ts#L313

I would be in favor of removing the check.  Beyond the performance benefits, I don't think it is intuitive to fill in data if it's not there, but you requested it - it feels like getting an `ArrayOutOfBounds` error and then papering over it by default.  At the minimum, I'd be happy to write some functionality that can turn this off, if you think it's doable i.e a `fill` option that, when false, does not fill in missing data but throws an error or the like, thereby making only one request.

**Comment by gzuidhof** [comment]
I think asking for forgiveness is better yes (so we can keep it down to one request) by removing that check. It just needs to be implemented :). Note should be taken that we need to make sure it actually does not exist (e.g. 404 in http store) and it's not just the request failing (e.g. access denied). In the second case we should probably throw an error to the user of the zarr library.

Filling in data that isn't there is the way zarr works and we shouldn't change that. One defines a `fill_value` that every chunk that doesn't exist yet or is newly created starts with. It makes sense as it's not out of bounds - it's within the bounds of the zarr array's size.

**Comment by ilan-gold** [comment]
Ok that makes sense - we can throw an error for non-404 repsonses.  What would you recommend for handling the 404 then? Fill the value in?

**Comment by gzuidhof** [comment]
Yes. Implementation-wise the store will have to throw a different error in either case, which can then be `instanceof`-checked and either ignored or rethrown.

**Comment by ilan-gold** [comment]
That sounds good.  I'm out of the office for the next few days, but I'll be getting to this soon.  Thanks!
