### ISSUE TITLE
Display Zarr Image

### ISSUE THREAD

**Issue by christophenoel** [gzuidhof/zarr.js#103]
Hi,

Amazing work ! 
Is there any possibility to display zarr as an image in the browser ?

Thanks.

**Comment by manzt** [comment]
Thanks for your interest in Zarr.js! I have two examples to share:

- An basic [Observable notebook](https://observablehq.com/d/c5020efb6bcb04d9) using Zarr.js to view zarr sample datasets from https://github.com/zarr-developers/zarr_implementations
- [Vizarr](https://github.com/hms-dbmi/vizarr) an interactive viewer built on https://github.com/hms-dbmi/viv (Zarr.js + Deck.gl)

**Comment by christophenoel** [comment]
Thanks. That's exactly what I was looking for !
