### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by manzt** [gzuidhof/zarr.js#2]
Looks like a really interesting project. Is there any road map for some documentation?

**Comment by gzuidhof** [comment]
Hi Trevor,

Better documentation and (especially) a nice set of examples are definitely on my to do list. It's a hobby project though, so no strict road map or timelines - but I hope to be able to spend quite some nights on it the coming month.

**Comment by manzt** [comment]
Yes definitely a nice set of examples. I'd be interested in helping with this!

**Comment by gzuidhof** [comment]
Hi Trevor, have a look [**here**](http://guido.io/zarr.js). Let me know what you think!

**Comment by manzt** [comment]
Wow, thank you! Will do.
