### ISSUE TITLE
no fetch polyfill for node environment

### ISSUE THREAD

**Issue by manzt** [gzuidhof/zarr.js#21]
Not only do we need to check for node environments when deciding between `ArrayBuffer` and `Buffer`, but `fetch` is not defined in Node.

https://github.com/gzuidhof/zarr.js/blob/5c6387cafb9891e15c085209d623bc4362ccbfd9/src/storage/httpStore.ts#L20-L28

I don't think there is a something native in Node, so I'm curious to hear your thoughts. However, the following fails:

```javascript
const zarr = require('zarr');

const config = {
  store: 'http://localhost:5000',
  path: 'dummy_data.zarr',
};

async function main() => {
  const z = await zarr.openArray(config);
  const data = await z.get([0, null, null]);
  console.log(data);
};

main();
```

```
(node:57635) UnhandledPromiseRejectionWarning: ReferenceError: fetch is not defined
```

**Comment by manzt** [comment]
I found this while looking for a fix for #10. Was curious about your thoughts, something like:

```javascript
interface StoreResponse {
    buffer: ArrayBuffer | Buffer;
    status: number;
}

export class HTTPStore implements AsyncStore<ArrayBuffer> {
...
async getItem(item: string): Promise<StoreResponse> {
        const url = new URL(item, this.url).href;
        const value = await fetch(url);
        const buffer = IS_NODE
            ? Buffer.from(await value.arrayBuffer()) // Node
            : await value.arrayBuffer(); // Browser
        return { buffer, status: value.status };
    }
}
```

And then handling the status within `core/index.ts`, but I'm running into issues since it wouldn't make sense to have the same `StoreResponse` for non `HTTPStore` s.

**Comment by gzuidhof** [comment]
For the first problem, I think the simple solution is to require something like `node-fetch` for node environments. I think that's acceptable as its a server/non-browser environment anyway.

For the first, I think we should throw an error and condition on the type of error. We actually already do that [**elsewhere**](https://github.com/gzuidhof/zarr.js/blob/master/src/core/index.ts#L545-L561). So we could throw a `KeyError` is the status is 404 (and maybe some others?), else we throw a different type of error.

**Comment by manzt** [comment]
This seems interesting, re: `@rollup/plugin-replace`:
https://nolanlawson.com/2017/01/09/how-to-write-a-javascript-package-for-both-node-and-the-browser/

Perhaps we can think of something similar for zarr.

**Comment by gzuidhof** [comment]
I think it's not worth the extra build complexity and having a separate output file per target. I think a runtime check is ok to determine which of the two to use. For the typing problems, maybe we can add a `global declare` somewhere.. It's a bit ugly, but should make the typescript compiler happy.
