### ISSUE TITLE
May already support Deno (better than Node?)

### ISSUE THREAD

**Issue by manzt** [gzuidhof/zarr.js#22]
Fun fact this works (since `fetch` is in the deno stdlib). I could add a note in the documentation.

```
$ deno --allow-net main.js
```

```javascript
//main.js
import { openArray } from 'https://unpkg.com/zarr@0.1.5/dist/zarr.es5.js';

const config = {
  store: 'http://localhost:5000',
  path: 'dummy_data.zarr',
};

const main = async () => {
  console.log('started');
  const z = await openArray(config);
  const data = await z.get([0, 0, null]);
  console.log(data);
};

main();
```

**Comment by manzt** [comment]
ha -- actually this works as well:

```
import { openArray } from 'https://unpkg.com/zarr@0.1.5/dist/zarr.es5.js';

const config = {
  store: 'http://localhost:5000',
  path: 'dummy_data.zarr',
};

const z = await openArray(config);
const data = await z.get([0, 0, null]);
console.log(data);
```
since Deno supports top-level await 😍

**Comment by gzuidhof** [comment]
That's cool, I hadn't heard of Deno before, watched the introducing talk now. I can't wait for something Electron-like to pop up for it. Because of the way the imports work, it also seems like a good fit for one-off scripts that has dependencies, very exciting :)

Not sure if it will ever get large adoption though..

**Comment by manzt** [comment]
I guess there isn't anything specific with this "issue" and we can close, but couldn't think of better way to share. I could add something to the docs, but that doesn't really seem appropriate either. Most people who are early on Deno will know how to import ESM modules.

After watching (Node creator) Ryan Dahl's [10 Things I Regret About Node.js](https://www.youtube.com/watch?v=M3BM9TB-8yA) and hearing him describe the idea of deno, I was excited to see how much it has grown in the [recent demo](https://www.youtube.com/watch?v=lcoU9jtsK24) prior to the 1.0 release this month. Typescript as a first class language is pretty cool as well, and creating named "executables" is something I really like.

Not sure about adoption either, but certainly an interesting project.
