### ISSUE TITLE
Data Types

### ISSUE THREAD

**Issue by ilan-gold** [gzuidhof/zarr.js#3]
Hello,

First off, I want to say "thank you!" for this project - it is very helpful!!  I have a question about data types: is there a reason the list here is a subset of the possible (in theory?) data types:

https://github.com/gzuidhof/zarr.js/blob/285d566471418286c3711c20e6806ca0b80f1aad/src/nestedArray/types.ts

For example, why is there no option for a `Uint32Array`?

Thanks!

**Comment by gzuidhof** [comment]
Hi ilan-gold, thanks for the kind words :)

There is no reason it's not supported, especially Uint32Array should be easy to add (just add it in a few places).

Some datatypes will be more difficult to support (e.g. `object` or the unicode length types), and others (64 bit integers) will [not be straightforward](http://guido.io/zarr.js/#/getting-started/remote-data?id=int64-support).

I'm happy to accept a PR adding support for whichever datatype you need :)

**Comment by ilan-gold** [comment]
I will do that then!

**Comment by ilan-gold** [comment]
Hello, how would you prefer i contribute?  I don't have permission to contribute to this repo.

**Comment by gzuidhof** [comment]
If you could create a pull request that would be perfect :) You will need to fork the repository, make your changes, and then the button should appear.

**Comment by gzuidhof** [comment]
Closing this issue, for anyone stumbling on this issue see PR #4.
