### ISSUE TITLE
Future codecs

### ISSUE THREAD

**Issue by manzt** [gzuidhof/zarr.js#40]
Related to #1. Currently we support `zlib` and `gzip` thanks to `pako`, but we will want to support more codecs in the future (especially BLOSC if/when that reaches the web).  I'm curious what your stance on bundling more third party libraries for decoding/encoding chunks. 

I'm not sure tree-shaking will work since the decoders needed for an `HTTPStore` won't be known until runtime. I would be in favor of creating something akin to `numcodecs` used in zarr and then offering some API to register a codec with `zarr.js`. 

```javascript
import { openArray } from 'zarr';
import { Zlib } from 'zarr-codecs'; 

const config = { 
    store: "http://localhost:8000/",
    path: "my_data.zarr",
    mode: "r",
    codec: Zlib,
};

z = await openArray(config);
```

I think we should include the default codec (zlib/gzip for zarr.js currently but BLOSC in the future) since it will be the most user friendly. We could keep track of what decoders are supported by `zarr-codecs` in `zarr` and give helpful warnings if someone needs to import a codec from `zarr-codecs`.

**Comment by manzt** [comment]
This setup might also expose an API to allow advanced users to do more bespoke things with their codecs, like configuring web-workers to perform decoding and encoding #33.

**Comment by manzt** [comment]
#1

**Comment by gzuidhof** [comment]
Sorry for the late response, I've been traveling the past weeks.

I agree that the codecs should live in a different repository as we add stuff like BLOSC, especially as they may grow in size quite a bit (could be a decently sized blob of WASM). I think we can follow the [same interface](https://numcodecs.readthedocs.io/en/latest/abc.html) as in Python numcodecs, it doesn't get much simpler :).

**Comment by gzuidhof** [comment]
It will also be useful outside of zarr, perhaps a name without `zarr` in it better reflects that?

**Comment by manzt** [comment]
> I think we can follow the same interface as in Python numcodecs, it doesn't get much simpler :).

Agreed.

> It will also be useful outside of zarr, perhaps a name without zarr in it better reflects that?

Want to use use the same name, `numcodecs`, on npm?

**Comment by gzuidhof** [comment]
Yes that sounds good :), feel free to create a repo if you're happy to own it.

I think [this interface](https://github.com/gzuidhof/zarr.js/blob/master/src/compression/types.ts) is pretty much the same as in numcodecs (maybe the return type should be uint8array though?). The stuff in the `compression` folder could be starting point

**Comment by manzt** [comment]
working on it :)

**Comment by kylebarron** [comment]
> I'm not sure tree-shaking will work since the decoders needed for an `HTTPStore` won't be known until runtime

In this case, you could consider dynamically loading the Blosc decompressor on the fly from a CDN, (e.g. `https://unpkg.com/numcodecs@0.1.1/dist/blosc.cjs`) only if a `HTTPStore` requires it. Then the minimum bundle size of `zarr.js` would be considerably smaller.

**Comment by manzt** [comment]
Thanks for the suggestion, @kylebarron. We've had a much more extensive conversation about future codecs in the `numcodecs` repo, where we've discussed something similar to what you've mentioned above: https://github.com/manzt/numcodecs.js/issues/2

The decision to include `blosc` currently is out of convenience since it is the default in `zarr-python`. Ideally, the codec registry would be completely dynamic and configurable by the end-user. This is why numcodecs is setup the way that it is, as separate code-split modules. I just haven't had the bandwidth to work on this further.

**Comment by manzt** [comment]
#63
