### ISSUE TITLE
Looking for examples using Zarr.js with visualization tools

### ISSUE THREAD

**Issue by jhamman** [gzuidhof/zarr.js#43]
Thanks for developing zarr.js! This is a very exciting advancement in the Zarr ecosystem.

I'm looking for some (simple) examples that utilize zarr.js with one or more visualization libraries (d3, plotty, etc). I'm also curious if there is any work underway to develop a "generic visualization" tool on top of Zarr.js?

**Comment by gzuidhof** [comment]
I don't think there are many examples out there yet, zarr.js is pretty new still. I have personally not used it in any open source projects yet for anything beyond prototyping.

As zarr.js returns one or more TypedArrays, any visualization should be able to take this as input fairly easily (maybe converting to a list of numbers first). As for a generic visualization tool being built: not that I'm aware of.

I'll add an example to the docs that uses zarr.js to plot some data in the browser, I expect that's the main reason why people would use this library. I'll ping here once I added it :)

**Comment by gzuidhof** [comment]
It's been a while, but finally I have created a notebook with a visualization from a zarr dataset:
https://starboard.gg/gz/visualizing-air-quality-nMntKEe
