### ISSUE TITLE
Throw more specific error with `getRawChunk`

### ISSUE THREAD

**Issue by manzt** [gzuidhof/zarr.js#47]
I'm working on an application requesting image tiles with `z.getRawChunk([z,y,x])`. 

I'm using a different library for fetching these indices which is unaware of tile boundaries. I'd like to `instanceof` the Error thrown by `getRawChunk` when a selection is out of bounds. Any opposition to creating a new error (`ChunkBoundsCheckError`) or rethrowing `BoundsCheckError` with a new message be alright? 

https://github.com/gzuidhof/zarr.js/blob/af88c471ae2b54f476a86b06a08b4d876a23409f/src/core/index.ts#L436-L441

**Comment by gzuidhof** [comment]
I would say rethrowing a `BoundCheckError` makes the most sense here, sure :)
