### ISSUE TITLE
Error: Buffer is not defined in exampleUMD

### ISSUE THREAD

**Issue by manzt** [gzuidhof/zarr.js#5]
I am unable to reconfigure the `exampleUMD()` from the docs for an `HTTPStore`. 
The example below is able to fetch the metadata for the zarr store, but Errors with:

`Error: Failed to load metadata for ZarrArray:ReferenceError: Buffer is not defined `

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>zarr.js demo</title>
  </head>
  <body>
    <script src="https://unpkg.com/zarr/dist/zarr.umd.js"></script>
    <script>
      const baseUrl = "https://raw.githubusercontent.com";
      const config = {
        store: `${baseUrl}/gzuidhof/zarr.js/master/fixtures/`,
        path: "simple.zarr",
        mode: "r"
      };
      async function exampleUMD() {
        const arrMeta = await fetch(
          `${config.store}${config.path}/.zarray`
        ).then(res => res.json());
        console.log(arrMeta);
        const z = await zarr.openArray(config);
        console.log(z);
      }
      exampleUMD();
    </script>
  </body>
</html>
```

I should note that the config works right out of the box with the bundler config provided with `create-react-app`. 

Steps to reproduce: 
```bash
npx create-react-app --use-npm zarr-demo && cd zarr-demo
npm install zarr
```
Edit `src/App.js`
```javascript
import React, { useEffect } from "react";
import { openArray } from "zarr";

function App() {
  const baseUrl = "https://raw.githubusercontent.com";
  useEffect(() => {
    async function loadArray() {
      const z = await openArray({
        store: `${baseUrl}/gzuidhof/zarr.js/master/fixtures/`,
        path: "simple.zarr",
        mode: "r"
      });
      console.log(z);
    }
    loadArray();
  }, []);

  return <div className="App"></div>;
}

export default App;
```

```bash
npm start
```

**Comment by gzuidhof** [comment]
Thank you for the detailed issue description, that was really helpful when debugging! :1st_place_medal: 

The problem was the use of Buffer (which is a Node only thing unless you import some polyfill of it, which I try to avoid in zarr). The bundler probably polyfills that for you, that's why it did work then.

I merged #6 and #7 to fix this issue, and pushed version 0.1.3, you may need to replace the import line with ```<script src="https://unpkg.com/zarr@0.1.3/dist/zarr.umd.js"></script>``` as your browser may cache the old version.

**Comment by gzuidhof** [comment]
![Screenshot from 2020-01-10 01 41 27](https://user-images.githubusercontent.com/1039510/72118848-66972780-334a-11ea-80a5-1c96e69722f8.png)

Output from your example now :+1:, that 404 is pretty ugly, but that's for another day.

**Comment by manzt** [comment]
Thanks for having a look into this. It's working for me now! 🔥
