### ISSUE TITLE
Use ES6 as module target

### ISSUE THREAD

**Issue by manzt** [gzuidhof/zarr.js#52]
I think we should be targeting modern ES6 (`ES2015`) for our module build. Users can transpile for their applications to target older browsers if necessary, but as a library I think we should be shipping with syntax that is closest to the source rather than forcing the compiler/bundler to provide a bunch of polyfills.

FWIW, I think we might actually be targeting ES6/ES2015, but the module naming is just off. In that case, we should just change the bundled extension to reflect this.

**Comment by gzuidhof** [comment]
I think we are targeting ES6, I agree that users can transpile into what makes sense for them (we could consider going to ES2018 or later even imo).

For some reason I thought the ES module as we export them were part of ES5, but they are actually E6. I agree it should be changed! I'll make a one line PR.
