### ISSUE TITLE
Documentation of HTTPStore

### ISSUE THREAD

**Issue by keller-mark** [gzuidhof/zarr.js#60]
In the documentation, it would be great if the all function prototypes and constructors could be defined.

For example, the documentation says that the HTTPStore uses `fetch` to make requests internally. As a user, I want to know if there is a way to customize the second argument of `fetch` (headers, etc) through either the call to `openArray` or the `HTTPStore` constructor, and to pass GET parameters that can be appended to the URL of each request (for example, to append `?token=jfdkaljfkdaljfkdsajlf` for authentication with each chunk request).

Is this currently possible, and if so, is it documented?

**Comment by manzt** [comment]
Good question! We are talking about something like this in #58, where the user can define what endpoint methods are supported (making `containsItem` more efficient if `HEAD` is supported). 

We could add `fetchOptions` to the constructor, where the options are just forwarded internally to all fetch requests. https://github.github.io/fetch/

**Comment by manzt** [comment]
FWIW in python `fsspec` allows you to forward `storage_options` for the HTTPFileSystem `MutableMapping`

**Comment by gzuidhof** [comment]
Right now it is not possible to pass in your own fetch options which is definitely a limitation. 

As long as this options object doesn't change between requests we could add it in the constructor for the HTTPStore, store it in a member variable, and use it for every fetch request.

Alternatively we could allow users to pass in their own fetch function, something like this:

```javascript
const myFetch = (url, init) => {
  init.headers = {
   "Authorization": "Bearer randomtoken23984u938jhasodfjhsdf",
  }
  return fetch(url, init)
}
const myStore = new HTTPStore("my-store-url.com/bla.zarr", {fetchFunction: myFetch});
```

**Comment by manzt** [comment]
Took way too long to follow up on this, sorry @keller-mark. I updated the docs and added `fetchOptions` and `supportedMethods` to the `HTTPStore` constructor. Should release soon!
