### ISSUE TITLE
Async fetching from HTTPStore

### ISSUE THREAD

**Issue by manzt** [gzuidhof/zarr.js#8]
I noticed that the indexer makes synchronous requests in `getSelection`. 

https://github.com/gzuidhof/zarr.js/blob/a22ba4717b5d660020036872a75129413821987b/src/core/index.ts#L287-L289

Is there a reason why each of these requests must be waited upon before filling the rest of the nested array? Is there some race condition that I'm not considering? 

I have this working locally and passing tests and would be happy to open a PR.
```javascript
await Promise.all(
  Array.from(
    indexer.iter(),
    proj => this.chunkGetItem(proj.chunkCoords, proj.chunkSelection, out, proj.outSelection, indexer.dropAxes)
  )
);
```

**Comment by manzt** [comment]
The performance benefits of this can be illustrated by adding a `setTimeout` in `chunkGetItem`:

```javascript
private async chunkGetItem<T extends TypedArray>(chunkCoords: number[], chunkSelection: DimensionSelection[], out: NestedArray<T>, outSelection: DimensionSelection[], dropAxes: null | number[]) {
    await new Promise(resolve => setTimeout(resolve, 200)); // add waiting time of 200ms for each request

    if (chunkCoords.length !== this._chunkDataShape.length) {
      throw new ValueError(`Inconsistent shapes: chunkCoordsLength: ${chunkCoords.length}, cDataShapeLength: ${this.chunkDataShape.length}`);
    }

    ...
```

**Comment by gzuidhof** [comment]
As I was implementing this I thought about this, and for sure this can and should be done asynchronously and was on my list of next steps, there is no race condition (as far as I can see).

The reason I left it out in the initial version is to keep parity with the Python implementation (the synchronous nature in the python lib will make this very difficult, whereas here we can do it quite elegantly!).

I think we should be slightly more careful as we may end up making a million requests all at once, so maybe we can wrap it in something that only opens XX simultaneous requests. For now we can just hardcode that count and make it configurable later.

I would love to see a PR for this!

---

Not completely unrelated: 
It's worth thinking about a way to communicate progress, it makes for a much better user experience in applications. Perhaps we should allow an optional callback that will be called with progress updates.

**Comment by manzt** [comment]
Ah I see what you mean. Were you thinking something like this?
```javascript
    const MAX_REQUEST_SIZE = 10;
    const allProjs = Array.from(indexer.iter());
    const projsChunks = Array(Math.ceil(allProjs.length / MAX_REQUEST_SIZE)).fill().map(_ => allProjs.splice(0, MAX_REQUEST_SIZE));
    for (const projs of projsChunks) {
      await Promise.all(projs.map(proj => this.chunkGetItem(proj.chunkCoords, proj.chunkSelection, out, proj.outSelection, indexer.dropAxes)));
    }
```

**Comment by gzuidhof** [comment]
I don't think we need to explicitly chunk it, we just want to limit the amount of concurrent requests. We could use [this library](https://www.npmjs.com/package/es6-promise-pool) or one of its alternatives.

---

For the callback, yes, something like that is exactly what I had in mind :). Perhaps instead we should pass in an object with the callback as a field (`progressCallback`?), that will leave future options/callbacks open. I can already think of one addition: `concurrencyLimit`, I think it makes sense for the store to pass a default value for it if it is not specified.

For the HTTP/2 multiplexing experiment - very cool! I don't know a lot about HTTP2, but I imagine that this will be especially beneficial for high latency storage (e.g. S3/GCS).

**Comment by manzt** [comment]
#11

**Comment by manzt** [comment]
PR #11 is relevant to this thread.

**Comment by manzt** [comment]
Feature added with #11

**Comment by gzuidhof** [comment]
I released version 0.1.4 with this change (and I added a test in #13).

**Comment by manzt** [comment]
Here is a JSFiddle with a progressbar!
https://jsfiddle.net/3ogk4L5h/5/

**Comment by gzuidhof** [comment]
😍
